package interpolacion;

import javax.swing.table.DefaultTableModel;

public class TablaChooser extends javax.swing.JDialog {
    static DefaultTableModel tblmodel;
    
    public TablaChooser(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        tblDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                { new Double(1.0),  new Double(0.7651977) },
                { new Double(1.3),  new Double(0.620086) },
                { new Double(1.6),  new Double(0.4554022) },
                { new Double(1.9),  new Double(0.2818186) },
                { new Double(2.2),  new Double(0.1103623) }
            },
            new String [] {
                "x", "f(x)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Double.class, java.lang.Double.class, java.lang.Boolean.class
            };
            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngroup = new javax.swing.ButtonGroup();
        rbtnTabla1 = new javax.swing.JRadioButton();
        rbtnTabla2 = new javax.swing.JRadioButton();
        rbtnTabla3 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDatos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(300, 47));
        setUndecorated(true);
        setOpacity(0.95F);
        setPreferredSize(new java.awt.Dimension(350, 410));
        setResizable(false);
        getContentPane().setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 10));

        btngroup.add(rbtnTabla1);
        rbtnTabla1.setText("Tabla 1");
        rbtnTabla1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnTabla1ActionPerformed(evt);
            }
        });
        getContentPane().add(rbtnTabla1);

        btngroup.add(rbtnTabla2);
        rbtnTabla2.setText("Tabla 2");
        rbtnTabla2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnTabla2ActionPerformed(evt);
            }
        });
        getContentPane().add(rbtnTabla2);

        btngroup.add(rbtnTabla3);
        rbtnTabla3.setText("Tabla 3");
        rbtnTabla3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnTabla3ActionPerformed(evt);
            }
        });
        getContentPane().add(rbtnTabla3);

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos"));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(340, 275));

        tblDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "i", "x", "f(x)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblDatos);
        if (tblDatos.getColumnModel().getColumnCount() > 0) {
            tblDatos.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        getContentPane().add(jScrollPane1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtnTabla1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnTabla1ActionPerformed
        tblDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                { new Double(1.0),  new Double(0.7651977) },
                { new Double(1.3),  new Double(0.620086) },
                { new Double(1.6),  new Double(0.4554022) },
                { new Double(1.9),  new Double(0.2818186) },
                { new Double(2.2),  new Double(0.1103623) }
            },
            new String [] {
                "x", "f(x)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Double.class, java.lang.Double.class, java.lang.Boolean.class
            };
            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
    }//GEN-LAST:event_rbtnTabla1ActionPerformed

    private void rbtnTabla2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnTabla2ActionPerformed
        tblDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                { new Double(0.2),  new Double(0.9798652) },
                { new Double(0.4),  new Double(0.9177710) },
                { new Double(0.6),  new Double(0.8080348) },
                { new Double(0.8),  new Double(0.6386093) },
                { new Double(1.0),  new Double(0.3843735) }
            },
            new String [] {
                "x", "f(x)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Double.class, java.lang.Double.class, java.lang.Boolean.class
            };
            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
    }//GEN-LAST:event_rbtnTabla2ActionPerformed

    private void rbtnTabla3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnTabla3ActionPerformed
        tblDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                { new Double(1930),  new Double(123203) },
                { new Double(1940),  new Double(131669) },
                { new Double(1950),  new Double(150697) },
                { new Double(1960),  new Double(179323) },
                { new Double(1970),  new Double(203212) },
                { new Double(1980),  new Double(226505) }
            },
            new String [] {
                "x", "f(x)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Double.class, java.lang.Double.class, java.lang.Boolean.class
            };
            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
    }//GEN-LAST:event_rbtnTabla3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        tblmodel = (DefaultTableModel) tblDatos.getModel();
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    public static DefaultTableModel showDialog(java.awt.Component parent){
        TablaChooser dialog = new TablaChooser(new javax.swing.JFrame(), true);
//        java.awt.Point p = parent.getLocation();
//        dialog.setLocation(p.x+parent.getWidth(), p.y+parent.getHeight());
        dialog.setLocationRelativeTo(parent);
        dialog.setLocationRelativeTo(parent);
        dialog.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                System.exit(0);
            }
        });
        dialog.setVisible(true);
        return tblmodel;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TablaChooser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TablaChooser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TablaChooser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TablaChooser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TablaChooser dialog = new TablaChooser(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btngroup;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbtnTabla1;
    private javax.swing.JRadioButton rbtnTabla2;
    private javax.swing.JRadioButton rbtnTabla3;
    private javax.swing.JTable tblDatos;
    // End of variables declaration//GEN-END:variables
}
